# fly.toml app configuration file generated for is-5700-final on 2024-12-16T22:43:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'is-5700-final'
primary_region = 'den'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
